// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cbart_cpp
RcppExport SEXP cbart_cpp(SEXP in_, SEXP ip_, SEXP iup_, SEXP inp_, SEXP ix_, SEXP iy_, SEXP ixp_, SEXP iux_, SEXP iuxp_, SEXP im_, SEXP inc_, SEXP ind_, SEXP iburn_, SEXP ipower_, SEXP ibase_, SEXP itau_, SEXP inu_, SEXP ilambda_, SEXP isigest_, SEXP iw_, SEXP idart_, SEXP itheta_, SEXP iomega_, SEXP igrp_, SEXP ia_, SEXP ib_, SEXP irho_, SEXP iaug_, SEXP inkeeptrain_, SEXP inkeeptest_, SEXP inkeeptestme_, SEXP inkeeptreedraws_, SEXP inprintevery_, SEXP Xinfo_, SEXP ilambda_prop_sd_, SEXP ilambda_start_, SEXP gamma_prop_sd_);
RcppExport SEXP _CBART_cbart_cpp(SEXP in_SEXP, SEXP ip_SEXP, SEXP iup_SEXP, SEXP inp_SEXP, SEXP ix_SEXP, SEXP iy_SEXP, SEXP ixp_SEXP, SEXP iux_SEXP, SEXP iuxp_SEXP, SEXP im_SEXP, SEXP inc_SEXP, SEXP ind_SEXP, SEXP iburn_SEXP, SEXP ipower_SEXP, SEXP ibase_SEXP, SEXP itau_SEXP, SEXP inu_SEXP, SEXP ilambda_SEXP, SEXP isigest_SEXP, SEXP iw_SEXP, SEXP idart_SEXP, SEXP itheta_SEXP, SEXP iomega_SEXP, SEXP igrp_SEXP, SEXP ia_SEXP, SEXP ib_SEXP, SEXP irho_SEXP, SEXP iaug_SEXP, SEXP inkeeptrain_SEXP, SEXP inkeeptest_SEXP, SEXP inkeeptestme_SEXP, SEXP inkeeptreedraws_SEXP, SEXP inprintevery_SEXP, SEXP Xinfo_SEXP, SEXP ilambda_prop_sd_SEXP, SEXP ilambda_start_SEXP, SEXP gamma_prop_sd_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type in_(in_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type ip_(ip_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type iup_(iup_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type inp_(inp_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type ix_(ix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type iy_(iy_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type ixp_(ixp_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type iux_(iux_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type iuxp_(iuxp_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type im_(im_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type inc_(inc_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type ind_(ind_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type iburn_(iburn_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type ipower_(ipower_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type ibase_(ibase_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type itau_(itau_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type inu_(inu_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type ilambda_(ilambda_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type isigest_(isigest_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type iw_(iw_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type idart_(idart_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type itheta_(itheta_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type iomega_(iomega_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type igrp_(igrp_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type ia_(ia_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type ib_(ib_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type irho_(irho_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type iaug_(iaug_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type inkeeptrain_(inkeeptrain_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type inkeeptest_(inkeeptest_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type inkeeptestme_(inkeeptestme_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type inkeeptreedraws_(inkeeptreedraws_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type inprintevery_(inprintevery_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type Xinfo_(Xinfo_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type ilambda_prop_sd_(ilambda_prop_sd_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type ilambda_start_(ilambda_start_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type gamma_prop_sd_(gamma_prop_sd_SEXP);
    rcpp_result_gen = Rcpp::wrap(cbart_cpp(in_, ip_, iup_, inp_, ix_, iy_, ixp_, iux_, iuxp_, im_, inc_, ind_, iburn_, ipower_, ibase_, itau_, inu_, ilambda_, isigest_, iw_, idart_, itheta_, iomega_, igrp_, ia_, ib_, irho_, iaug_, inkeeptrain_, inkeeptest_, inkeeptestme_, inkeeptreedraws_, inprintevery_, Xinfo_, ilambda_prop_sd_, ilambda_start_, gamma_prop_sd_));
    return rcpp_result_gen;
END_RCPP
}
// norm
double norm(double x, double y);
RcppExport SEXP _CBART_norm(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(norm(x, y));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP mc_cores_openmp();

static const R_CallMethodDef CallEntries[] = {
    {"_CBART_cbart_cpp", (DL_FUNC) &_CBART_cbart_cpp, 37},
    {"_CBART_norm", (DL_FUNC) &_CBART_norm, 2},
    {"mc_cores_openmp", (DL_FUNC) &mc_cores_openmp, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_CBART(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
