# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cbart_cpp <- function(in_, ip_, iup_, inp_, ix_, iy_, ixp_, iux_, iuxp_, im_, inc_, ind_, iburn_, ipower_, ibase_, itau_, inu_, ilambda_, isigest_, iw_, idart_, itheta_, iomega_, igrp_, ia_, ib_, irho_, iaug_, inkeeptrain_, inkeeptest_, inkeeptestme_, inkeeptreedraws_, inprintevery_, Xinfo_, ilambda_prop_sd_, ilambda_start_, gamma_prop_sd_) {
    .Call(`_CBART_cbart_cpp`, in_, ip_, iup_, inp_, ix_, iy_, ixp_, iux_, iuxp_, im_, inc_, ind_, iburn_, ipower_, ibase_, itau_, inu_, ilambda_, isigest_, iw_, idart_, itheta_, iomega_, igrp_, ia_, ib_, irho_, iaug_, inkeeptrain_, inkeeptest_, inkeeptestme_, inkeeptreedraws_, inprintevery_, Xinfo_, ilambda_prop_sd_, ilambda_start_, gamma_prop_sd_)
}

norm <- function(x, y) {
    .Call(`_CBART_norm`, x, y)
}

